import localFont from "next/font/local";
import "./globals.css";
import HeaderLayout from '../components/Header'
import ReduxProvider from '../components/Wrap';
 import { QueryClient,QueryClientProvider } from "react-query";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();
export default function RootLayout({ children, auth }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
        <QueryClientProvider client={queryClient}>
          <HeaderLayout children={auth}></HeaderLayout>
          {children}
          </QueryClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
